# 1. Definir la versión exacta de Python para quitar el Warning
sonar.python.version=3.12

# 2. Indicarle dónde encontrará el reporte de cobertura
sonar.python.coverage.reportPaths=coverage.xml

# 3. Excluir carpetas que no son código fuente para no arruinar las métricas
sonar.exclusions=venv/**, allure-results/**, datasets/**, docs/**, **/*.json, **/*.md