name: Auditoria IA - Voice Framework

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches: 
      - "main"
      - "develop"
  workflow_dispatch:

jobs:
  test-ai:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: ⚙️ Instalar FFmpeg (Requisito del Sistema)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: 📦 Instalar Dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary :all: --no-binary openai-whisper -r requirements.txt

      - name: 🤖 Levantar el Mock Bot en segundo plano
        run: |
          python mock_bot.py &
          sleep 5 

      - name: 🧪 Ejecutar Auditoría BDD y Medir Cobertura
        run: |
          echo "========================================================"
          echo "🚀 INICIANDO AUDITORÍA PARA LA RAMA: ${{ github.ref_name }}"
          echo "========================================================"
          
          echo -e "\n📖 LEYENDO ESCENARIOS GHERKIN (BUSINESS RULES):"
          echo "--------------------------------------------------------"
          cat features/evaluacion_voz.feature
          echo "--------------------------------------------------------"
          
          echo -e "\n⚙️ EJECUTANDO PRUEBAS..."
          pytest tests/test_bdd_voz.py -v -s --alluredir=allure-results --cov=. --cov-report=xml
        continue-on-error: true

      - name: 📊 Escáner de SonarCloud 
        uses: SonarSource/sonarcloud-github-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=grupocinte
            -Dsonar.projectKey=GrupoCinte_framework-qa-iavoice
            -Dsonar.python.version=3.12
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=datasets/**,docs/**,allure-results/**,venv/**,**/*.md,**/*.json
            -Dsonar.coverage.exclusions=mock_bot.py

      - name: 📈 Guardar Resultados de Allure (Artefacto)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 7